### ISSUE TITLE
Issue with KFM Mac

### ISSUE THREAD

**Issue by darrenramlal** [synapsepd/MacOS-OneDrive-KFM#1]
Hi there, im having an issue with the setup. This step : sudo defaults write "/Library/Preferences/com.cambridgeconsultants.onedrive-kfm" EnableKFM -bool YES

will always let me type in the admin password but won't accept the credentials. The other steps do .

**Comment by samspade21** [comment]
The sudo command looks correct.  You can always do a "sudo -s" to enter a cmd as root.  Then do your "defaults write" command in that context.
