### ISSUE TITLE
Are you still working on this?

### ISSUE THREAD

**Issue by awvalentine** [synapsepd/MacOS-OneDrive-KFM#3]
I have this working on my Mac and was wondering if you are still working on it?

**Comment by gyverdsm** [comment]
How did you get this working? we installed the outset pkg, along with the kfm pkg and setup the profile. but nothing is happening. We do not see anything really syncing aside from the onedrive folder.

**Comment by samspade21** [comment]
Just want to make sure you did step 2 and set all of your defaults write commands.  Once you have and you reboot (to kick off the outset script) and you don't see it running - take a look in your console for any logs.  You should be able to filter them based on a search for "OneDrive-KFM"

**Comment by samspade21** [comment]
> I have this working on my Mac and was wondering if you are still working on it?

We have a number of small improvements that we have made but are still testing before committing back to GitHub.  But the tool is in production for our organization.  The next major release - we plan on including an "uninstall" option that can be used in the event that Microsoft implements this natively.

**Comment by ehouston3** [comment]
Thank you for creating this. I was thinking of "rolling my own" using symlinks and rsync. I hope MS pulls this into OneDrive for business on Mac soon.  Thanks again!
