### ISSUE TITLE
Seems to be incompatible with iCloud Drive

### ISSUE THREAD

**Issue by anxanywhere** [synapsepd/MacOS-OneDrive-KFM#7]
When iCloud Drive is enabled, after reboot, the links will be replaced respectively by the directories `Desktop` and `Documents` and the links moved inside those folders.

Right after install of MacOS-OneDrive-KFM and before reboot:

```
/Users/me/Desktop -> /Users/me/OneDrive - Company, Inc/Desktop
/Users/me/Documents -> /Users/me/OneDrive - Company, Inc/Documents
```

After reboot:

```
/Users/me/Desktop/Desktop -> /Users/me/OneDrive - Company, Inc/Desktop
/Users/me/Documents/Documents -> /Users/me/OneDrive - Company, Inc/Documents
```

Turning off iCloud Drive seems to fix this.

Br,
ANx

**Comment by lilongwe** [comment]
Hi

Seems like a great project and amazing work!

Before installing I was wondering if this would work with iCloud drive as I would love to have the files synced to iCloud and On Drive if at all possible. It might be over kill but I am generally using my Desktop for One Drive and Documents for iCloud.

Many thanks for any help.

**Comment by samspade21** [comment]
It has not been tested with iCloud.  I would bet it will not work correctly.  As this uses sym links and iCloud uses a native API.  FYI though OneDrive is moving to support this nativity this fall.  We will work on an “uninstaller” so that a transition can be made to the supported process.

**Comment by lilongwe** [comment]
Thanks for responding. I did assume both couldn’t be used simultaneously on the same folders. It’s great to hear Microsoft are going native. Do you have a link to that feature so I can monitor its release.

**Comment by samspade21** [comment]
Here is the Microsoft anouncment: https://techcommunity.microsoft.com/t5/microsoft-onedrive-blog/microsoft-works-to-ensure-a-great-onedrive-experience-on-apple/ba-p/2400803
